version: '3'

services:
  database:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest-api-docker
      MYSQL_USER: application
      MYSQL_PASSWORD: password
  app:
    depends_on:
      - database
    image: openjdk:11
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    restart: always
    environment:
      ENVIRONMENT: prd
      SERVER_PORT: 8082
      CONTEXT_PATH: /api
      DB_URL: jdbc:mysql://database:3306/rest-api-docker
      DB_USERNAME: application
      DB_PASSWORD: password
